//! Per-CPU instruction reference pages, generated from the `isa` crate.
//!
//! Docs-site plan R1 and R5: the reference comes from the spec, so a spec
//! change regenerates the page and a new CPU documents itself the moment its
//! spec lands. Nothing here is hand-authored, and `cargo xtask docs --check`
//! fails if a committed page has fallen behind.
//!
//! # What is not here
//!
//! **Provenance links.** R1 also wants each page to link into the umbrella
//! `reference/` datasheet library. The spec has no field for it: ten of the
//! nineteen modules carry a `**Provenance.**` paragraph in their doc comment
//! and nine — including 6502, Z80 and 65816 — carry nothing. Generating a
//! citation would mean inventing one, which is worse than having none.
//!
//! **Six CPUs.** The 68000, 6809, TMS9900, PDP-11, CP1610 and Z8000 encode
//! with models a form table cannot describe, and are listed on the index page
//! rather than left quietly absent.
//!
//! Four of them export a `SET: InstructionSet` whose `instructions` is
//! **empty** — a placeholder beside the real, bespoke table. That is a trap
//! worth naming: reading the exports alone suggests they are on the standard
//! model, and generating from them produces a page confidently reporting zero
//! instructions. [`every_listed_cpu_has_instructions`] exists so that cannot
//! happen quietly again.

use std::fmt::Write as _;

/// One CPU whose spec can be rendered as a form table.
struct Cpu {
    /// URL and file stem.
    slug: &'static str,
    /// The spec module this comes from, named on the page so a reader who
    /// wants the encoding truth can go straight to it.
    module: &'static str,
    set: &'static isa::InstructionSet,
}

/// Every CPU the reference covers, in the order the book lists them: the
/// machines people arrive looking for, then the rest by lineage.
fn cpus() -> Vec<Cpu> {
    vec![
        Cpu {
            slug: "mos6502",
            module: "mos6502",
            set: &isa::mos6502::SET,
        },
        Cpu {
            slug: "mos65816",
            module: "mos65816",
            set: &isa::mos65816::SET,
        },
        Cpu {
            slug: "huc6280",
            module: "huc6280",
            set: &isa::huc6280::SET,
        },
        Cpu {
            slug: "z80",
            module: "z80",
            set: &isa::z80::SET,
        },
        Cpu {
            slug: "z80n",
            module: "z80",
            set: &isa::z80::NEXT,
        },
        Cpu {
            slug: "sm83",
            module: "sm83",
            set: &isa::sm83::SET,
        },
        Cpu {
            slug: "i8080",
            module: "i8080",
            set: &isa::i8080::SET,
        },
        Cpu {
            slug: "m6800",
            module: "m6800",
            set: &isa::m6800::SET,
        },
        Cpu {
            slug: "cdp1802",
            module: "cdp1802",
            set: &isa::cdp1802::SET,
        },
        Cpu {
            slug: "i8048",
            module: "i8048",
            set: &isa::i8048::SET,
        },
        Cpu {
            slug: "scmp",
            module: "scmp",
            set: &isa::scmp::SET,
        },
        Cpu {
            slug: "f8",
            module: "f8",
            set: &isa::f8::SET,
        },
        Cpu {
            slug: "s2650",
            module: "s2650",
            set: &isa::s2650::SET,
        },
        Cpu {
            slug: "tms7000",
            module: "tms7000",
            set: &isa::tms7000::SET,
        },
    ]
}

/// A page the generator owns entirely: path under the book's `src`, and its
/// content.
pub struct Page {
    pub path: String,
    pub body: String,
}

/// Render every page the instruction reference owns — one per CPU, plus the
/// index that lists them.
pub fn pages() -> Vec<Page> {
    let cpus = cpus();
    let mut out: Vec<Page> = cpus
        .iter()
        .map(|cpu| Page {
            path: format!("instructions/{}.md", cpu.slug),
            body: render_cpu(cpu),
        })
        .collect();
    out.push(Page {
        path: "instructions.md".to_string(),
        body: render_index(&cpus),
    });
    out
}

/// The `SUMMARY.md` lines listing the instruction reference, so a new CPU
/// appears in the sidebar without anyone remembering to add it.
pub fn summary_lines() -> String {
    let mut out = String::from("- [Instruction reference](instructions.md)\n");
    for cpu in cpus() {
        let _ = writeln!(out, "  - [{}](instructions/{}.md)", cpu.set.cpu, cpu.slug);
    }
    out
}

/// The note every generated page opens with, so nobody edits one by hand and
/// loses the edit on the next run.
fn generated_note(module: &str) -> String {
    format!(
        "<!-- Generated by `cargo xtask docs` from `crates/isa/src/{module}.rs`. \
         Edits here are overwritten; change the spec instead. -->\n"
    )
}

fn render_index(cpus: &[Cpu]) -> String {
    let mut out = String::from("# Instruction reference\n\n");
    out.push_str(&generated_note("*"));
    out.push_str(
        "\nOne page per CPU, generated from the instruction-set specification the\n\
         assembler encodes with. A spec change regenerates these pages, and CI fails\n\
         if a committed page has fallen behind — so what you read here is what the\n\
         assembler does, not what someone remembered it did.\n\n",
    );

    let _ = writeln!(out, "| CPU | Mnemonics | Forms | Byte order |");
    out.push_str("|---|---|---|---|\n");
    for cpu in cpus {
        let forms: usize = cpu.set.instructions.iter().map(|i| i.forms.len()).sum();
        let _ = writeln!(
            out,
            "| [{}](instructions/{}.md) | {} | {} | {} |",
            cpu.set.cpu,
            cpu.slug,
            cpu.set.instructions.len(),
            forms,
            match cpu.set.endianness {
                isa::Endianness::Little => "little-endian",
                isa::Endianness::Big => "big-endian",
            }
        );
    }

    out.push_str(
        "\n## Not generated\n\n\
         Six CPUs encode with models a form table cannot describe, so they have no\n\
         page here rather than a misleading one. All six assemble and disassemble\n\
         normally; only the *reference table* is missing.\n\n\
         **Word-oriented, class and base:** TI TMS9900, DEC PDP-11, GI CP1610 and\n\
         Zilog Z8000. An instruction is an opcode *word* whose operand fields are\n\
         bits within it, selected by a class mask — so there is no \"opcode bytes,\n\
         then operand bytes\" to tabulate. The first three share one model and want\n\
         one renderer between them.\n\n\
         **Motorola 68000** — field-packed effective addresses: an operand's meaning\n\
         lives in bit fields inside the opcode word, and how many extension words\n\
         follow depends on the mode those bits select.\n\n\
         **Motorola 6809** — computed operands. Its postbyte selects an indexing\n\
         mode whose length depends on the mode chosen.\n\n\
         The same field-packed gap affects the spec-query and cycle-analyzer work,\n\
         so the answer wants deciding once rather than three times.\n\n\
         ## Provenance\n\n\
         These specs are authored from datasheets in the family's primary reference\n\
         library, not extracted from an emulator's decode loop. That provenance is\n\
         recorded per module in prose today, and unevenly: ten of the nineteen carry\n\
         a citation and nine do not. Linking each page to its datasheet is the\n\
         other half of this reference, and it waits on the citation being data\n\
         rather than a paragraph.\n",
    );
    out
}

fn render_cpu(cpu: &Cpu) -> String {
    let mut out = format!("# {}\n\n", cpu.set.cpu);
    out.push_str(&generated_note(cpu.module));

    let forms: usize = cpu.set.instructions.iter().map(|i| i.forms.len()).sum();
    let undocumented: usize = cpu
        .set
        .instructions
        .iter()
        .flat_map(|i| i.forms)
        .filter(|f| f.undocumented)
        .count();

    let _ = write!(
        out,
        "\n{} mnemonics, {} encoded forms, {}. Generated from \
         [`crates/isa/src/{}.rs`](https://github.com/asm198x/asm198x/blob/main/crates/isa/src/{}.rs).\n",
        cpu.set.instructions.len(),
        forms,
        match cpu.set.endianness {
            isa::Endianness::Little => "operands little-endian",
            isa::Endianness::Big => "operands big-endian",
        },
        cpu.module,
        cpu.module,
    );
    if undocumented > 0 {
        let _ = write!(
            out,
            "\n{undocumented} of those forms are undocumented opcodes, marked \
             **undocumented** below. They encode, because real programs use them.\n"
        );
    }
    out.push_str("\nCycle counts show the base cost; `+p` is an extra cycle when an\nindexed access crosses a page boundary, `+t` when a branch is taken.\n");

    for instruction in cpu.set.instructions {
        let _ = write!(
            out,
            "\n## {}\n\n{}\n\n",
            instruction.mnemonic, instruction.summary
        );
        out.push_str("| Mode | Opcode | Operands | Bytes | Cycles | Flags |\n");
        out.push_str("|---|---|---|---|---|---|\n");
        for form in instruction.forms {
            let _ = writeln!(
                out,
                "| {}{} | `{}` | {} | {} | {} | {} |",
                form.mode,
                if form.undocumented {
                    " **undocumented**"
                } else {
                    ""
                },
                hex(form.opcode, form.suffix),
                operands(form.operands),
                form.len(),
                cycles(form.cycles),
                if form.flags.is_empty() {
                    "—"
                } else {
                    form.flags
                },
            );
        }
    }
    out
}

/// Opcode bytes as hex. A suffix byte — the Z80 `DD CB <d> <op>` group, whose
/// final opcode byte follows the displacement — is shown in its real position
/// so the row reads as the bytes actually land.
fn hex(opcode: &[u8], suffix: &[u8]) -> String {
    let head = opcode
        .iter()
        .map(|b| format!("{b:02X}"))
        .collect::<Vec<_>>()
        .join(" ");
    if suffix.is_empty() {
        head
    } else {
        let tail = suffix
            .iter()
            .map(|b| format!("{b:02X}"))
            .collect::<Vec<_>>()
            .join(" ");
        format!("{head} .. {tail}")
    }
}

fn operands(operands: &[isa::Operand]) -> String {
    if operands.is_empty() {
        return "—".to_string();
    }
    operands
        .iter()
        .map(|o| {
            let kind = match o.kind {
                isa::OperandKind::Immediate => "imm",
                isa::OperandKind::ImmediateBe => "imm-be",
                isa::OperandKind::Address => "addr",
                isa::OperandKind::RelativePc => "rel",
                isa::OperandKind::Displacement => "disp",
            };
            format!("{kind}{}", o.bytes * 8)
        })
        .collect::<Vec<_>>()
        .join(", ")
}

fn cycles(cycles: isa::Cycles) -> String {
    let mut out = cycles.base.to_string();
    if cycles.branch_taken > 0 {
        out.push_str(" +t");
    }
    if cycles.page_cross > 0 {
        out.push_str(" +p");
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Every CPU listed must actually carry instructions.
    ///
    /// Four modules export a `SET: InstructionSet` whose `instructions` is
    /// empty, standing beside the real bespoke table — `tms9900`, `pdp11`,
    /// `cp1610`, `z8000`, and `mos6809` does the same. Listing one here
    /// generates a page that states, in a confident table, that the CPU has
    /// zero instructions. It is wrong in the most credible possible way, and
    /// only a count catches it.
    #[test]
    fn every_listed_cpu_has_instructions() {
        let empty: Vec<&str> = cpus()
            .iter()
            .filter(|cpu| cpu.set.instructions.is_empty())
            .map(|cpu| cpu.slug)
            .collect();
        assert!(
            empty.is_empty(),
            "these CPUs would generate an empty reference page: {}\n\
             Their `SET` is a placeholder; the real spec is a bespoke table that \
             needs its own renderer.",
            empty.join(", ")
        );
    }

    /// Slugs become file names and URLs, so a duplicate would silently have one
    /// page overwrite another.
    #[test]
    fn slugs_are_unique() {
        let mut seen = std::collections::BTreeSet::new();
        for cpu in cpus() {
            assert!(seen.insert(cpu.slug), "duplicate slug `{}`", cpu.slug);
        }
    }
}
